match_key : new_match_key
calc_key  : new_calc_key
keys      : 
    internet:
        pattern: /new_pattern/
        process_method: sum_bytes
    sms:
        pattern: /SMS/
        process_method: count_occurrences
    local_cellphone:
        pattern: /Locais.*Celulares/
        process_method: sum_minutes
    local_phone:
        pattern: /Locais.*Fixos/
        process_method: sum_minutes
    long_distance_cellphone:
        pattern: /Longa Distância.*Celulares/
        process_method: sum_minutes
    long_distance_phone:
        pattern: /Longa Distância/
        process_method: sum_minutes